spring.datasource.url=jdbc:mysql://localhost:3308/ecommerce
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

#spring.security.user.name = yogi
#spring.security.user.password = Yogi123
#spring.security.user.role = USER,ADMIN


